const axios = require('axios');

const apiKey = process.env.TWOFACTOR_API_KEY;
const templateName = process.env.TWOFACTOR_TEMPLATE_NAME || 'SST';

/**
 * Dispatches an Autogenerated OTP via 2Factor.in and returns the Session ID
 * @param {string} to - Recipient phone number (e.g. +919876543210 or 9876543210)
 * @returns {Promise<string|null>} OTP Session ID
 */
const sendTwoFactorOtp = async (to) => {
  if (!apiKey) {
    console.warn('[2Factor] Missing 2Factor API Key in environment. Skipping OTP dispatch.');
    return null;
  }

  // Clean phone number (strip '+' and ensure country prefix for India 2Factor dispatches)
  let cleanTo = to.replace(/\+/g, '').trim();
  if (cleanTo.length === 10) {
    cleanTo = '91' + cleanTo;
  }

  const useDefaultTemplate = !templateName || templateName === 'DEFAULT' || templateName.trim() === '';
  const url = useDefaultTemplate
    ? `https://2factor.in/API/V1/${apiKey}/SMS/${cleanTo}/AUTOGEN`
    : `https://2factor.in/API/V1/${apiKey}/SMS/${cleanTo}/AUTOGEN/${templateName}`;

  try {
    const response = await axios.get(url);
    if (response.data && response.data.Status === 'Success') {
      console.log(`[2Factor] Autogenerated OTP sent. Session ID:`, response.data.Details);
      return response.data.Details; // This is the OTP SessionID
    } else {
      throw new Error(response.data?.Details || 'Failed to dispatch autogenerated OTP.');
    }
  } catch (error) {
    const errorDetails = error.response ? JSON.stringify(error.response.data) : error.message;
    console.error(`[2Factor] Failed to send autogenerated OTP to ${cleanTo}:`, errorDetails);
    throw error;
  }
};

/**
 * Verifies the user-entered OTP against the 2Factor Session ID
 * @param {string} sessionId - The OTP Session ID returned during dispatch
 * @param {string} otp - The OTP entered by the user
 * @returns {Promise<boolean>} True if OTP is matched
 */
const verifyTwoFactorOtp = async (sessionId, otp) => {
  if (!apiKey) {
    console.warn('[2Factor] Missing 2Factor API Key. Bypassing verification.');
    return false;
  }

  const url = `https://2factor.in/API/V1/${apiKey}/SMS/VERIFY/${sessionId}/${otp}`;

  try {
    const response = await axios.get(url);
    if (response.data && response.data.Status === 'Success' && response.data.Details === 'OTP Matched') {
      console.log(`[2Factor] OTP matched successfully for Session ID: ${sessionId}`);
      return true;
    }
    return false;
  } catch (error) {
    // 2Factor returns 400 or error status if OTP is mismatch
    console.warn(`[2Factor] OTP Verification failed or mismatched:`, error.response?.data || error.message);
    return false;
  }
};

module.exports = {
  sendTwoFactorOtp,
  verifyTwoFactorOtp
};
